version: "3"

networks:
  public-net:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.100
  site-1:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  site-2:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24
  site-3:
    ipam:
      driver: default
      config:
        - subnet: 10.30.0.0/24

services:
  turn-server:
    image: ghcr.io/webmeshproj/turn:latest
    networks:
      public-net:
        ipv4_address: 10.1.0.1
    entrypoint:
      - /webmesh-turn
      - --public-ip=10.1.0.1
      - --enable-campfire=true
    restart: on-failure

  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      public-net:
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --mesh.wait-campfire-uri=camp://webmesh/?0=turn:10.1.0.1:3478#R0kITeF6rXzNd9tqavra6szH9cRcJbGp
      - --services.api.webrtc=true
      - --services.api.mesh=true
    ports:
      - 8443:8443
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    depends_on:
      - turn-server

  site-1-peer:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
      site-1:
    hostname: site-1-peer
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --mesh.join-campfire-uri=camp://webmesh/?0=turn:10.1.0.1:3478#R0kITeF6rXzNd9tqavra6szH9cRcJbGp
      - --mesh.direct-peers=site-2-peer,site-3-peer
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    depends_on:
      - turn-server
      - bootstrap-node

  site-2-peer:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
      site-2:
    hostname: site-2-peer
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --mesh.join-campfire-uri=camp://webmesh/?0=turn:10.1.0.1:3478#R0kITeF6rXzNd9tqavra6szH9cRcJbGp
      - --mesh.direct-peers=site-1-peer,site-3-peer
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    depends_on:
      - turn-server
      - bootstrap-node

  site-3-peer:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
      site-3:
    hostname: site-3-peer
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --mesh.join-campfire-uri=camp://webmesh/?0=turn:10.1.0.1:3478#R0kITeF6rXzNd9tqavra6szH9cRcJbGp
      - --mesh.direct-peers=site-1-peer,site-2-peer
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    depends_on:
      - turn-server
      - bootstrap-node
